version: '3'

services:
  db:
    environment:
      POSTGRES_DB: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_USER: chat
    image: postgres:9.4
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: backend
    command: npm run dev
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - 9000:9000
    links:
      - db

  dev:
    build: frontend
    environment:
      ENDPOINT: ${ENDPOINT}
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 8000:8000

volumes:
  dbdata:
