version: '2'

services:
  backend:
    build: backend
    command: npm run dev
    volumes:
      - ./backend/src:/usr/src/app/src
      - dbdata:/usr/src/app/db
    ports:
      - 9000:9000

volumes:
  dbdata:
